config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: { format: :json}  do
    get 'events/important'
    get 'events/all'
    get 'bookings/booking_total'
    get 'employees', to: 'employees#index'
  end

  resources :bookings
  resources :children
  resources :booking_service_lines
  resources :customer_bookings
  get 'booking_employees/:booking_id/multiadd', to: 'booking_employees#index', as: 'booking_employees_multiadd'
  post 'booking_employees/save', to: 'booking_employees#save', as: 'booking_employees_save'
  post 'booking_employees/add', to: 'booking_employees#new', defaults: { format: :js }
  post 'booking_employees/:booking_id/multiadd/save', to: 'booking_employees#save'
  resources :booking_employees
  get 'employees/child_parent_data_set', to: 'employees#child_parent_data_set'
  resources :employees
  resources :employee_types
  resources :discount_types
  resources :customers do
    collection { post :import }
  end
  resources :child_parents
  resources :service_fees
  get 'booking_employees/multiadd', to: 'booking_employees#multiadd'
  get 'general_settings/index'
  post 'customers/get_latest_bookings', to: 'customers#get_latest_bookings', defaults: {format: :json}

  devise_for :users
  get 'index/Index'

  # lol
  get 'supersecret', to: 'index#Julius'
  get 'burntbanana', to: redirect("https://youtu.be/c7tOAGY59uQ?t=18s")


  root 'index#Index'

  # lookup customers in booking form
  post 'customers/lookup', to: 'customers#lookup', defaults: {format: :json}

  # adding services to booking form
  post 'bookings/:id/add_service', to: 'bookings#add_service', defaults: {format: :js}

  # reports
  get 'reports/customer', to: 'reports#customers_by_bookings'
  get 'reports/customer.json', to: "reports#customers_by_bookings", defaults: {format: :json}, as: 'reports_customers_by_bookings'
  get 'reports/month_birthdays', to: 'reports#month_birthdays'
  get 'reports/month_birthdays.json', to: "reports#month_birthdays", defaults: {format: :json}, as: 'reports_month_birthdays_json'
  get 'reports/popular_services', to: 'reports#popular_services'
  post 'reports/popular_services.json', to: 'reports#popular_services', defaults: {format: :json}, as: 'reports_popular_services_json'
  get 'reports/bookings', to: 'reports#bookings'
  post 'reports/bookings.json', to: 'reports#bookings', defaults: {format: :json}, as: 'reports_bookings_json'
  get 'reports/revenue_by_service', to: 'reports#revenue_by_service'
  post 'reports/revenue_by_service.json', to: 'reports#revenue_by_service', defaults: {format: :json}, as: 'reports_revenue_by_service_json'
  get 'reports/booking_per_dt', to: 'reports#booking_per_dt'
  post 'reports/bookings_per_dt.json', to: 'reports#booking_per_dt', defaults: {format: :json}, as: 'reports_bookings_per_dt_json'
  get 'dashboard', to: 'dashboard#index'

  #mailer routes
  get '/reminder/all', to: 'bookings#send_monthly_reminder'
  get '/reminder/bday', to: 'customers#send_bday_reminder'
  get '/reminder/:booking_id', to: 'bookings#send_reminder'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #change service_fees.json
  get 'as_json.json', to: 'service_fees#as_json', defaults: {format: :json}
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<link href="assets/dashboard/sb-admin-2.css" rel="stylesheet">
<link href="assets/dashboard/metisMenu.min.css" rel="stylesheet">
<script src="assets/dashboard/metisMenu.min.js"></script>
<script src="assets/dashboard/sb-admin-2.js"></script>


  <div class="form-row">
    <div class="col-lg-12">
      <h1 class="page-header">Dashboard</h1>
    </div>
    <!-- /.col-lg-12 -->
  </div>
  <!-- /.row -->
  <div style="margin-top: 3em" class="form-group row">
    <div class="col-lg-3 col-md-6">
      <div class="card border-primary">
        <div class="card-body">
          <div class="form-row">
            <div class="col">
              <i class="far fa-money-bill-alt fa-5x"></i>
            </div>
            <div class="col text-right">
              <div class="huge">$<%= Booking.where('end_date between ? and ?', DateTime.now.beginning_of_month, DateTime.now.beginning_of_day).sum(&:total) %></div>
              <div>Revenue since beginning of the month</div>
            </div>
          </div>
        </div>
        <a href="<%= reports_bookings_path %>">
          <div class="card-footer">
            <span class="pull-left">View Details</span>
            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
            <div class="clearfix"></div>
          </div>
        </a>
      </div>
    </div>
    <div class="col-lg-3 col-md-6">
      <div class="card border-primary">
        <div class="card-body">
          <div class="form-row">
            <div class="col">
              <i style="color: #3B5998" class="fab fa-facebook-square fa-5x"></i>
            </div>
            <div class="col text-right">
              <div class="huge"><%= Customer.where.not(facebook_handle: [nil, ""]).count %></div>
              <div>Customer(s) using Facebook</div>
            </div>
          </div>
        </div>
        <a href="<%= customers_path %>">
          <div class="card-footer">
            <span class="pull-left">View Details</span>
            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
            <div class="clearfix"></div>
          </div>
        </a>
      </div>
    </div>
    <div class="col-lg-3 col-md-6">
      <div class="card border-primary">
        <div class="card-body">
          <div class="form-row">
            <div class="col">
              <i style="color: #1dcaff" class="fab fa-twitter-square fa-5x"></i>
            </div>
            <div class="col text-right">
              <div class="huge"><%= Customer.where.not(twitter_handle: [nil, ""]).count %></div>
              <div>Customer(s) using Twitter</div>
            </div>
          </div>
        </div>
        <a href="<%= customers_path %>">
          <div class="card-footer">
            <span class="pull-left">View Details</span>
            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
            <div class="clearfix"></div>
          </div>
        </a>
      </div>
    </div>
    <div class="col-lg-3 col-md-6">
      <div class="card border-primary">
        <div class="card-body">
          <div class="form-row">
            <div class="col">
              <i style="color: #fb3958" class="fab fa-instagram fa-5x"></i>
            </div>
            <div class="col text-right">
              <div class="huge"><%= Customer.where.not(instagram_handle: [nil, ""]).count %></div>
              <div>Customer(s) using Instagram</div>
            </div>
          </div>
        </div>
        <a href="<%= customers_path %>">
          <div class="card-footer">
            <span class="pull-left">View Details</span>
            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
            <div class="clearfix"></div>
          </div>
        </a>
      </div>
    </div>
  </div>
  <!-- /.row -->
  <div class="row">
    <div class="col-lg-8">
      <div class="card card-primary">
        <div class="card-header">
          <i class="fas fa-chart-line"></i> Bookings per service by weeks
          <div class="float-right dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              More reports ...
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <%= link_to('Customer Reports', reports_customer_path, method: :get, class: "dropdown-item") %>
              <%= link_to('Month Birthdays', reports_month_birthdays_path, method: :get, class: "dropdown-item") %>
              <%= link_to('Popular Services', reports_popular_services_path, method: :get, class: "dropdown-item") %>
              <%= link_to('Bookings', reports_bookings_path, method: :get, class: "dropdown-item") %>
              <%= link_to('Revenue', reports_revenue_by_service_path, method: :get, class: "dropdown-item") %>
              <%= link_to('Discounts', discount_types_path, class: "dropdown-item") %>
            </div>
          </div>
        </div>

        <!-- /.card-header -->
        <div class="card-body">
          <%= line_chart ServiceFee.all.map { |service|
            {name: service.service_desc.to_s, data: service.bookings.group_by_week(:start_date).count}
          }, suffix: " bookings",xtitle: "Time", ytitle: "Number of bookings", label: "Number of bookings", id: 'chart', colors: ["#b00", "#666", "#CA6240", "#A57261", "#5FB04B", "#A4D897", "#4EBB81", "#45E1B9", "#3DB4D6", "#3D7CD6", "#543DD6", "#793DD6", "#AA3DD6", "#D63DD4", "#E772E6", "#E772B7" ]  %>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card .card-primary -->
    </div>
      <!-- /.col-lg-8 -->
    <div class="col-lg-4">
      <div class="card card-default">
        <div class="card-header">
          <i class="fa fa-bell fa-fw"></i> Notifications card
        </div>
        <!-- /.card-header -->
        <div class="card-body">
          <div class="list-group">
            <a href="<%= customers_path %>" class="list-group-item">
              <i class="fas fa-plus-circle fa-fw"></i> Newest Customer
              <span class="pull-right text-muted small"><em><%= Customer.last.cf_name + Customer.last.cl_name %><%= Customer.last.created_at.strftime(" on %m/%d/%Y at %I:%M%p") %></em>
                                    </span>
            </a>
            <a href="<%= root_path %>" class="list-group-item">
              <i class="far fa-bookmark fa-fw"></i> Newest Booking
              <span class="pull-right text-muted small"><em><%= Booking.last.bookingdetails%><%= Customer.last.created_at.strftime(" on %m/%d/%Y at %I:%M%p") %></em>
                                    </span>
            </a>
            <a href="#" class="list-group-item">
              <i class="fa fa-envelope fa-fw"></i> Last birthday reminder email sent today
              <span class="pull-right text-muted small"><em>27 minutes ago</em>
                                    </span>
            </a>
            <a href="#" class="list-group-item">
              <i class="fa fa-envelope fa-fw"></i> Last booking reservation reminder email sent today
              <span class="pull-right text-muted small"><em>43 minutes ago</em>
                                    </span>
            </a>
            <a class="list-group-item">
              <i class="fas fa-sign-in-alt fa-fw"></i> Last login at
              <span class="pull-right text-muted small"><em><%= current_user.last_sign_in_at.in_time_zone("Central Time (US & Canada)").strftime(" on %m/%d/%Y at %I:%M%p")%></em>
                                    </span>
            </a>
          </div>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card .card-default-->
    </div>
      <!-- /.col-lg-4 -->
    </div>
    <!-- /.row -->