config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: { format: :json}  do
    get 'events/important'
    get 'events/all'
    get 'bookings/booking_total'
    get 'employees', to: 'employees#index'
  end

  resources :bookings
  resources :children
  resources :booking_service_lines
  resources :customer_bookings
  get 'booking_employees/:booking_id/multiadd', to: 'booking_employees#index', as: 'booking_employees_multiadd'
  post 'booking_employees/save', to: 'booking_employees#save', as: 'booking_employees_save'
  post 'booking_employees/add', to: 'booking_employees#new', defaults: { format: :js }
  post 'booking_employees/:booking_id/multiadd/save', to: 'booking_employees#save'
  resources :booking_employees
  get 'employees/child_parent_data_set', to: 'employees#child_parent_data_set'
  resources :employees
  resources :employee_types
  resources :discount_types
  resources :customers do
    collection { post :import }
  end
  resources :child_parents
  resources :service_fees
  get 'booking_employees/multiadd', to: 'booking_employees#multiadd'
  get 'general_settings/index'
  post 'customers/get_latest_bookings', to: 'customers#get_latest_bookings', defaults: {format: :json}

  devise_for :users
  get 'index/Index'

  # lol
  get 'supersecret', to: 'index#Julius'
  get 'burntbanana', to: redirect("https://youtu.be/c7tOAGY59uQ?t=18s")


  root 'index#Index'

  # lookup customers in booking form
  post 'customers/lookup', to: 'customers#lookup', defaults: {format: :json}

  # adding services to booking form
  post 'bookings/:id/add_service', to: 'bookings#add_service', defaults: {format: :js}

  # reports
  get 'reports/customer', to: 'reports#customers_by_bookings'
  get 'reports/customer.json', to: "reports#customers_by_bookings", defaults: {format: :json}, as: 'reports_customers_by_bookings'
  get 'reports/month_birthdays', to: 'reports#month_birthdays'
  get 'reports/month_birthdays.json', to: "reports#month_birthdays", defaults: {format: :json}, as: 'reports_month_birthdays_json'
  get 'reports/popular_services', to: 'reports#popular_services'
  post 'reports/popular_services.json', to: 'reports#popular_services', defaults: {format: :json}, as: 'reports_popular_services_json'
  get 'reports/bookings', to: 'reports#bookings'
  post 'reports/bookings.json', to: 'reports#bookings', defaults: {format: :json}, as: 'reports_bookings_json'
  get 'reports/revenue_by_service', to: 'reports#revenue_by_service'
  post 'reports/revenue_by_service.json', to: 'reports#revenue_by_service', defaults: {format: :json}, as: 'reports_revenue_by_service_json'
  get 'reports/booking_per_dt', to: 'reports#booking_per_dt'
  post 'reports/bookings_per_dt.json', to: 'reports#booking_per_dt', defaults: {format: :json}, as: 'reports_bookings_per_dt_json'
  get 'dashboard', to: 'dashboard#index'

  #mailer routes
  get '/reminder/all', to: 'bookings#send_monthly_reminder'
  get '/reminder/bday', to: 'customers#send_bday_reminder'
  get '/reminder/:booking_id', to: 'bookings#send_reminder'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #change service_fees.json
  get 'as_json.json', to: 'service_fees#as_json', defaults: {format: :json}
end

app/controllers/discount_types_controller.rb
class DiscountTypesController < ApplicationController
  before_action :set_discount_type, only: [:show, :edit, :update, :destroy]

  # GET /discount_types
  # GET /discount_types.json
  def index
    @discount_types = DiscountType.all
    respond_to do |format|
      format.html
      format.json { render json: DiscountTypesDatatable.new(view_context) }
    end
  end

  # GET /discount_types/1
  # GET /discount_types/1.json
  def show
  end

  # GET /discount_types/new
  def new
    @discount_type = DiscountType.new
  end

  # GET /discount_types/1/edit
  def edit
  end

  # POST /discount_types
  # POST /discount_types.json
  def create
    @discount_type = DiscountType.new(discount_type_params)

    respond_to do |format|
      if @discount_type.save
        format.html { redirect_to @discount_type, notice: 'Discount type was successfully created.' }
        format.json { render :show, status: :created, location: @discount_type }
      else
        format.html { render :new }
        format.json { render json: @discount_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discount_types/1
  # PATCH/PUT /discount_types/1.json
  def update
    respond_to do |format|
      if @discount_type.update(discount_type_params)
        format.html { redirect_to @discount_type, notice: 'Discount type was successfully updated.' }
        format.json { render :show, status: :ok, location: @discount_type }
      else
        format.html { render :edit }
        format.json { render json: @discount_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discount_types/1
  # DELETE /discount_types/1.json
  def destroy
    @discount_type.destroy
    respond_to do |format|
      format.html { redirect_to discount_types_url, notice: 'Discount type was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discount_type
      @discount_type = DiscountType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discount_type_params
      params.require(:discount_type).permit(:discount_type, :deleted_at)
    end
end

app/helpers/discount_types_helper.rb
module DiscountTypesHelper
end

app/views/discount_types/_form.html.erb
<div style="padding: 2em" class="card">
<%= form_with(model: discount_type, local: true) do |form| %>
  <% if discount_type.errors.any? %>
      <div class="row">
        <div class="col-md-4">
          <div id="error_explanation">
            <div class="alert alert-dismissible alert-danger">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              <strong><%= pluralize(discount_type.errors.count, "error") %> prohibited this discount_type from being saved:</strong>
            </div>
        <ul class="list-group">
          <li class="list-group-item d-flex justify-content-between align-items-center"><% discount_type.errors.full_messages.each do |message| %></li>
        <li><%= message %></li>
      <% end %>
        </ul>
        </div>
      </div>
    </div>
    <br>
  <% end %>
    <div class="form-group row">
      <div class="col-sm-3">
        <%= form.label :discount_type %>
        <%= form.text_field :discount_type, id: :discount_type_discount_type, class:'form-control' %>
      </div>
    </div>
      <div class="form-row">
        <%= form.submit class: 'btn btn-success' %>
      </div>
    <div style="margin-top: 2em" class="form-row"><%= link_to 'Back', discount_types_path,class: 'btn btn-success' %>
    </div>
<% end %>
</div>

app/views/discount_types/edit.html.erb
<h1>Editing Discount Type</h1>

<%= render 'form', discount_type: @discount_type %>

<%= link_to 'Show', @discount_type %> |
<%= link_to 'Back', discount_types_path %>

app/views/discount_types/index.html.erb
<div class="container-fluid">

  <div class="card-title"><h3>Discount Types</h3></div>
<div class="card-body">
  <%= link_to 'New Discount Type', new_discount_type_path, {class: 'btn btn-success', style: 'margin-bottom: 30px'} %>
  <%= content_tag :table, id: "discount_type", class: 'table table-striped table-bordered', role: :datatable, data: { url: discount_types_path(format: :json)} do %>
  <thead>
  <tr id="header">
    <th>ID</th>
    <th>Discount_type</th>
    <th>Action</th>
  </tr>
  </thead>

  <tbody>
  </tbody>

<% end %></div>

<br></div>

app/views/discount_types/new.html.erb
<h1>New Discount Type</h1>

<%= render 'form', discount_type: @discount_type %>

app/views/discount_types/show.html.erb
<div class="card" style="width: 50%; padding: 1em; margin: 1em">
  <div class="card-body">
    <h5 class="card-title">Discount type you just created!</h5>
    <p class="card-text">
      <strong>Discount type:</strong>
      <%= @discount_type.discount_type %>
    </p>
    <div class="form-row">
      <!--Passing employee values to new booking form. -->
      <div class="col-md-5">
        <%= link_to 'Edit', edit_discount_type_path(@discount_type), {class: 'btn btn-primary'} %>
      </div>
      <div class="col-md-2">
        <%= link_to 'Back', discount_types_path, method: :get, class: 'btn btn-success' %>
      </div>
    </div>
  </div>
</div>