config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: { format: :json}  do
    get 'events/important'
    get 'events/all'
    get 'bookings/booking_total'
    get 'employees', to: 'employees#index'
  end

  resources :bookings
  resources :children
  resources :booking_service_lines
  resources :customer_bookings
  get 'booking_employees/:booking_id/multiadd', to: 'booking_employees#index', as: 'booking_employees_multiadd'
  post 'booking_employees/save', to: 'booking_employees#save', as: 'booking_employees_save'
  post 'booking_employees/add', to: 'booking_employees#new', defaults: { format: :js }
  post 'booking_employees/:booking_id/multiadd/save', to: 'booking_employees#save'
  resources :booking_employees
  get 'employees/child_parent_data_set', to: 'employees#child_parent_data_set'
  resources :employees
  resources :employee_types
  resources :discount_types
  resources :customers do
    collection { post :import }
  end
  resources :child_parents
  resources :service_fees
  get 'booking_employees/multiadd', to: 'booking_employees#multiadd'
  get 'general_settings/index'
  post 'customers/get_latest_bookings', to: 'customers#get_latest_bookings', defaults: {format: :json}

  devise_for :users
  get 'index/Index'

  # lol
  get 'supersecret', to: 'index#Julius'
  get 'burntbanana', to: redirect("https://youtu.be/c7tOAGY59uQ?t=18s")


  root 'index#Index'

  # lookup customers in booking form
  post 'customers/lookup', to: 'customers#lookup', defaults: {format: :json}

  # adding services to booking form
  post 'bookings/:id/add_service', to: 'bookings#add_service', defaults: {format: :js}

  # reports
  get 'reports/customer', to: 'reports#customers_by_bookings'
  get 'reports/customer.json', to: "reports#customers_by_bookings", defaults: {format: :json}, as: 'reports_customers_by_bookings'
  get 'reports/month_birthdays', to: 'reports#month_birthdays'
  get 'reports/month_birthdays.json', to: "reports#month_birthdays", defaults: {format: :json}, as: 'reports_month_birthdays_json'
  get 'reports/popular_services', to: 'reports#popular_services'
  post 'reports/popular_services.json', to: 'reports#popular_services', defaults: {format: :json}, as: 'reports_popular_services_json'
  get 'reports/bookings', to: 'reports#bookings'
  post 'reports/bookings.json', to: 'reports#bookings', defaults: {format: :json}, as: 'reports_bookings_json'
  get 'reports/revenue_by_service', to: 'reports#revenue_by_service'
  post 'reports/revenue_by_service.json', to: 'reports#revenue_by_service', defaults: {format: :json}, as: 'reports_revenue_by_service_json'
  get 'reports/booking_per_dt', to: 'reports#booking_per_dt'
  post 'reports/bookings_per_dt.json', to: 'reports#booking_per_dt', defaults: {format: :json}, as: 'reports_bookings_per_dt_json'
  get 'dashboard', to: 'dashboard#index'

  #mailer routes
  get '/reminder/all', to: 'bookings#send_monthly_reminder'
  get '/reminder/bday', to: 'customers#send_bday_reminder'
  get '/reminder/:booking_id', to: 'bookings#send_reminder'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #change service_fees.json
  get 'as_json.json', to: 'service_fees#as_json', defaults: {format: :json}
end

app/controllers/employee_types_controller.rb
class EmployeeTypesController < ApplicationController
  before_action :set_employee_type, only: [:show, :edit, :update, :destroy]

  # GET /employee_types
  # GET /employee_types.json
  def index
    @employee_types = EmployeeType.all
  end

  # GET /employee_types/1
  # GET /employee_types/1.json
  def show
  end

  # GET /employee_types/new
  def new
    @employee_type = EmployeeType.new
  end

  # GET /employee_types/1/edit
  def edit
  end

  # POST /employee_types
  # POST /employee_types.json
  def create
    @employee_type = EmployeeType.new(employee_type_params)

    respond_to do |format|
      if @employee_type.save
        format.html { redirect_to @employee_type, notice: 'Employee type was successfully created.' }
        format.json { render :show, status: :created, location: @employee_type }
      else
        format.html { render :new }
        format.json { render json: @employee_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employee_types/1
  # PATCH/PUT /employee_types/1.json
  def update
    respond_to do |format|
      if @employee_type.update(employee_type_params)
        format.html { redirect_to @employee_type, notice: 'Employee type was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee_type }
      else
        format.html { render :edit }
        format.json { render json: @employee_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employee_types/1
  # DELETE /employee_types/1.json
  def destroy
    @employee_type.destroy
    respond_to do |format|
      format.html { redirect_to employee_types_url, notice: 'Employee type was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee_type
      @employee_type = EmployeeType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_type_params
      params.require(:employee_type).permit(:employee_type, :deleted_at)
    end
end

app/helpers/employee_types_helper.rb
module EmployeeTypesHelper
end

app/views/employee_types/_form.html.erb
<div style="padding: 2em" class="card">
  <%= form_with(model: employee_type, local: true) do |form| %>
    <% if employee_type.errors.any? %>
      <div class="row">
        <div class="col-md-4">
          <div id="error_explanation">
            <div class="alert alert-dismissible alert-danger">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              <strong><%= pluralize(employee_type.errors.count, "error") %> prohibited this type of employee from being saved:</strong>
            </div>
            <ul class="list-group">
              <li class="list-group-item d-flex justify-content-between align-items-center"><% employee_type.errors.full_messages.each do |message| %></li>
                  <li><%= message %></li>
                <% end %>
                </ul>
          </div>
        </div>
      </div>
      <br>
    <% end %>
    <div style="margin:1em 0em 1em 0em" class="form-row">
      <div class="col-sm-2">
        <%= form.submit class: 'btn btn-success' %>
      </div>
      <div class="col-md-2">
        <%= link_to 'Back', employee_types_path, class: 'btn btn-success' %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-sm-3">
        <%= form.label :employee_type %>
        <%= form.text_field :employee_type, id: :employee_type_employee_type, class: 'form-control' %>
      </div>
    </div>
<% end %>
</div>

app/views/employee_types/edit.html.erb
<h1>Editing Employee Type</h1>

<%= render 'form', employee_type: @employee_type %>

app/views/employee_types/index.html.erb
<h1>Employee Types</h1>
<%= link_to 'New Employee Type', new_employee_type_path, {class: 'btn btn-success', style: 'margin-bottom: 30px'} %>
<table id="employee_type">
  <thead>
    <tr>
      <th>Employee type</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @employee_types.each do |employee_type| %>
      <tr>
        <td><%= employee_type.employee_type %></td>
        <td><%= link_to 'Edit', edit_employee_type_path(employee_type), class: 'btn btn-success' %> | <%= link_to 'Delete', employee_type, method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/employee_types/new.html.erb
<h1>New Employee Type</h1>

<%= render 'form', employee_type: @employee_type %>

app/views/employee_types/show.html.erb
<div class="card" style="width: 50%; padding: 1em; margin: 1em">
  <div class="card-body">
    <h5 class="card-title">Employee type you just created!</h5>
    <p class="card-text">
      <strong>Employee type:</strong>
      <%= @employee_type.employee_type %>
    </p>
    <div class="form-row">
      <!--Passing employee values to new booking form. -->
      <div class="col-md-5">
        <%= link_to 'Edit', edit_employee_type_path(@employee_type), {class: 'btn btn-primary'} %>
      </div>
      <div class="col-md-2">
        <%= link_to 'Back', employee_types_path, method: :get, class: 'btn btn-success' %>
      </div>
    </div>
  </div>
</div>