config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: { format: :json}  do
    get 'events/important'
    get 'events/all'
    get 'bookings/booking_total'
    get 'employees', to: 'employees#index'
  end

  resources :bookings
  resources :children
  resources :booking_service_lines
  resources :customer_bookings
  get 'booking_employees/:booking_id/multiadd', to: 'booking_employees#index', as: 'booking_employees_multiadd'
  post 'booking_employees/save', to: 'booking_employees#save', as: 'booking_employees_save'
  post 'booking_employees/add', to: 'booking_employees#new', defaults: { format: :js }
  post 'booking_employees/:booking_id/multiadd/save', to: 'booking_employees#save'
  resources :booking_employees
  get 'employees/child_parent_data_set', to: 'employees#child_parent_data_set'
  resources :employees
  resources :employee_types
  resources :discount_types
  resources :customers do
    collection { post :import }
  end
  resources :child_parents
  resources :service_fees
  get 'booking_employees/multiadd', to: 'booking_employees#multiadd'
  get 'general_settings/index'
  post 'customers/get_latest_bookings', to: 'customers#get_latest_bookings', defaults: {format: :json}

  devise_for :users
  get 'index/Index'

  # lol
  get 'supersecret', to: 'index#Julius'
  get 'burntbanana', to: redirect("https://youtu.be/c7tOAGY59uQ?t=18s")


  root 'index#Index'

  # lookup customers in booking form
  post 'customers/lookup', to: 'customers#lookup', defaults: {format: :json}

  # adding services to booking form
  post 'bookings/:id/add_service', to: 'bookings#add_service', defaults: {format: :js}

  # reports
  get 'reports/customer', to: 'reports#customers_by_bookings'
  get 'reports/customer.json', to: "reports#customers_by_bookings", defaults: {format: :json}, as: 'reports_customers_by_bookings'
  get 'reports/month_birthdays', to: 'reports#month_birthdays'
  get 'reports/month_birthdays.json', to: "reports#month_birthdays", defaults: {format: :json}, as: 'reports_month_birthdays_json'
  get 'reports/popular_services', to: 'reports#popular_services'
  post 'reports/popular_services.json', to: 'reports#popular_services', defaults: {format: :json}, as: 'reports_popular_services_json'
  get 'reports/bookings', to: 'reports#bookings'
  post 'reports/bookings.json', to: 'reports#bookings', defaults: {format: :json}, as: 'reports_bookings_json'
  get 'reports/revenue_by_service', to: 'reports#revenue_by_service'
  post 'reports/revenue_by_service.json', to: 'reports#revenue_by_service', defaults: {format: :json}, as: 'reports_revenue_by_service_json'
  get 'reports/booking_per_dt', to: 'reports#booking_per_dt'
  post 'reports/bookings_per_dt.json', to: 'reports#booking_per_dt', defaults: {format: :json}, as: 'reports_bookings_per_dt_json'
  get 'dashboard', to: 'dashboard#index'

  #mailer routes
  get '/reminder/all', to: 'bookings#send_monthly_reminder'
  get '/reminder/bday', to: 'customers#send_bday_reminder'
  get '/reminder/:booking_id', to: 'bookings#send_reminder'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #change service_fees.json
  get 'as_json.json', to: 'service_fees#as_json', defaults: {format: :json}
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def booking_per_dt
    hash = Booking.where("extract(year from start_date) = ?", params[:year]).group(:discount_type_id).count
    new_hash = hash.collect{|k, v| [DiscountType.where(id: k).pluck(:discount_type), v]}

    respond_to do |format|
      format.html { render }
      format.json { render json: new_hash }
    end
  end


  def customers_by_bookings
    customers = Customer.joins(:customer_bookings).group(:id).order("COUNT('customers.id') DESC").first(5)
    @hash = Hash.new
    customers.map { |customer|
      increment_hash_by(@hash, customer, customer.bookings.count)
    }

    respond_to do |format|
      format.html { render }
      format.json { render json: @hash}
    end
  end

  def month_birthdays
    children = Child.all
    hash = Hash.new
    children.map { |child|
      unless child.c_birthday.nil? then
        month = child.c_birthday.strftime("%B")
        unless hash[month].nil?
          hash[month] += 1
        else
          hash[month] = 1
        end
      end
    }
    respond_to do |format|
      format.html { render }
      format.json {render json: hash}
    end
  end

  def popular_services
    services = nil
    @hash = Hash.new

    if params.has_key?(:year)
      if params.has_key?(:month)
        services = BookingServiceLine.select('service_fees.service_desc').by_month(params[:year].to_i, Date::MONTHNAMES.index(params[:month])).joins(:service_fee).group('service_fees.service_desc').order('COUNT(service_fee_id) DESC').count.first(8)
      elsif params.has_key?(:quarter)
        services = BookingServiceLine.select('service_fees.service_desc').by_quarter(params[:year].to_i, params[:quarter].to_i).joins(:service_fee).group('service_fees.service_desc').order('COUNT(service_fee_id) DESC').count.first(8)
      else
        services = BookingServiceLine.select('service_fees.service_desc').by_year(params[:year].to_i).joins(:service_fee).group('service_fees.service_desc').order('COUNT(service_fee_id) DESC').count.first(8)
      end
    else
      services = BookingServiceLine.select('service_fees.service_desc').joins(:service_fee).group('service_fees.service_desc').order('COUNT(service_fee_id) DESC').count.first(5)
    end
    services.map { |service, count| increment_hash_by(@hash, service, count ) } 
    respond_to do |format|
      format.html { render }
      format.json { render json: @hash }
    end
  end

  def bookings
    @hash = Hash.new
    bookings = nil

    if params.has_key?(:year)
      bookings = Booking.by_year(params[:year].to_i)  
    else
      bookings = Booking.all
    end

    case params[:scope]
      when "monthly"
        bookings.map { |x| increment_hash(@hash, x.start_date.strftime("%B")) }
      when "yearly"
        bookings.map { |x| increment_hash(@hash, x.start_date.strftime("%Y")) }
      when "quarterly"
        bookings.map { |x|
          month = x.start_date.strftime("%-m").to_i
          if month.between?(1,3)
            increment_hash(@hash, "Quarter 1")
          elsif month.between?(4,6)
            increment_hash(@hash, "Quarter 2")
          elsif month.between?(7,9)
            increment_hash(@hash, "Quarter 3")
          else
            increment_hash(@hash, "Quarter 4")
          end
        }
      else
        bookings.map { |x| increment_hash(@hash, "Overall") }
    end

    respond_to do |format|
      format.html { render }
      format.json { render json: @hash }
    end

  end

  def revenue_by_service
    services = nil
    @hash = Hash.new
    eval_proc = nil

    if params.has_key?(:year)
      if params.has_key?(:month)
        services = BookingServiceLine.by_month(params[:year].to_i, Date::MONTHNAMES.index(params[:month])) 
      elsif params.has_key?(:quarter)
        services = BookingServiceLine.by_quarter(params[:year].to_i, params[:quarter].to_i)
      else
        services = BookingServiceLine.by_year(params[:year].to_i)
      end
    else
      services = BookingServiceLine.all
    end   

    services.map{ |service_line|
      if service_line.service_fee.std_price != 0
        increment_hash_by(@hash, service_line.service_fee, service_line.service_fee.std_price)
      end
    }
    respond_to do |format|
      format.html { render }
      format.json { render json: @hash }
    end
  end


  def evaluate(hash, val, proc)
    if proc.call
      increment_hash(@hash, val)
    end
  end

  def increment_hash(hash, val)
    increment_hash_by(hash, val, 1)
  end

  def increment_hash_by(hash, key, val)
    unless val.nil?
      hash[key] = hash[key].nil? ?  val : hash[key] += val
    end

  end

end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/booking_per_dt.html.erb
<div>
  <%= form_tag(reports_booking_per_dt_path,method: 'get', :remote => "true", id: 'form') do %>
    <% available_years = BookingServiceLine.all.map { |x| [x.date_of_booking("%Y"), x.date_of_booking("%Y")] }.uniq { |x| x } %>
    <%= select_tag(:year, options_for_select(available_years, 2018  ),id: 'select_tag_year', prompt: 'Choose a Year...') %>
    <%= submit_tag "Load", id: 'loadBtn', class: 'btn btn-info' %>
  <% end %>
</div>
<div style="margin-top: 1em" class="card">
  <%= column_chart reports_booking_per_dt_url(year: Time.zone.now.year), label: 'Number of bookings',xtitle: "Discount type", ytitle: "Number of bookings", id:'booking_chart', download: true %>
</div>

app/views/reports/bookings.html.erb
<div class="grid-layout-reports">
  <div class="grid-reports-selection">
    <%= link_to "Overall", "", class: "btn btn-secondary active", data: { scope: "" }%>
    <%= link_to "Monthly", "", class: "btn btn-secondary", data: { scope: "monthly", controls: "yearly" } %>
    <%= link_to "Quarterly", "", class: "btn btn-secondary", data: { scope: "quarterly", controls: "yearly" } %>
    <%= link_to "Yearly", "", class: "btn btn-secondary", data: { scope: "yearly", controls: "yearly" } %>
  </div>
  <div class="grid-reports-controls">
    <% available_years = Booking.all.map { |x| [x.start_date.strftime("%Y"), x.start_date.strftime("%Y")] }.uniq { |x| x }  %>
    <%= select_tag(:year_select, options_for_select(available_years), class: "control hidden", name: "year", data: { scope: "yearly quarterly monthly" } ) %>
  </div>
  <div class="grid-reports-chart m-md-5">
    <%= column_chart reports_bookings_json_path, xtitle: "Date", ytitle: "Amount"  %>
  </div>
</div>

app/views/reports/customers_by_bookings.html.erb
<div class="m-md-5"><%= column_chart reports_customers_by_bookings_path, xtitle: "Top 5 Customers", ytitle: "Bookings" %></div>

app/views/reports/month_birthdays.html.erb
<div class="m-md-5"><%= column_chart reports_month_birthdays_json_path, label: 'Number of birthdays', xtitle: "Month", ytitle: "Birthdays" %>
</div>

app/views/reports/popular_services.html.erb
<%= csrf_meta_tags %>
<div class="grid-layout-reports">
  <div class="grid-reports-selection">
    <%= link_to "Overall", reports_popular_services_path, class: "btn btn-secondary" %>
    <%= link_to "Monthly", reports_popular_services_path, class: "btn btn-secondary", data: { controls: "monthly" } %>
    <%= link_to "Quarterly", reports_popular_services_path, class: "btn btn-secondary", data: { controls: "quarterly"  } %>
    <%= link_to "Yearly", reports_popular_services_path, class: "btn btn-secondary", data: { controls: "yearly" } %>
  </div>
  <div class="grid-reports-controls">
    <%= select_tag(:quarter_select,
                   options_for_select(
                       [
                           ['Quarter 1', '1'],
                           ['Quarter 2', '2'],
                           ['Quarter 3', '3'],
                           ['Quarter 4', '4']
                       ], 1
                   ), class: "control hidden", name: "quarter", data: { scope: "quarterly" } ) %>
    <% available_months = BookingServiceLine.all.map { |x| [x.date_of_booking("%B"), x.date_of_booking("%B")] }.uniq { |x| x } %>
    <% available_years = BookingServiceLine.all.map { |x| [x.date_of_booking("%Y"), x.date_of_booking("%Y")] }.uniq { |x| x } %>

    <%= select_tag(:month_select, options_for_select(available_months), class: "control hidden", name: "month", data: { scope: "monthly" } ) %>
    <%= select_tag(:year_select, options_for_select(available_years), class: "control hidden", name: "year", data: { scope: "yearly quarterly monthly" } ) %>
  </div>
  <div class="grid-reports-chart m-md-5">
    <%= column_chart reports_popular_services_json_path, xtitle: "Services", ytitle: "Total" %>
  </div>
</div>

app/views/reports/revenue_by_service.html.erb
<div class="grid-layout-reports">
  <div class="grid-reports-selection">
    <%= link_to "Overall", reports_popular_services_path, class: "btn btn-secondary", data: {controls: "" } %>
    <%= link_to "Monthly", reports_popular_services_path, class: "btn btn-secondary", data: { controls: "monthly" } %>
    <%= link_to "Quarterly", reports_popular_services_path, class: "btn btn-secondary", data: { controls: "quarterly"  } %>
    <%= link_to "Yearly", reports_popular_services_path, class: "btn btn-secondary", data: { controls: "yearly" } %>
  </div>
  <div class="grid-reports-controls">
    <%= select_tag(:quarter_select, 
          options_for_select(
            [ 
              ['Quarter 1', '1'],
              ['Quarter 2', '2'],
              ['Quarter 3', '3'],
              ['Quarter 4', '4']
            ], 1
    ), name: "quarter", class: "control hidden", data: { scope: "quarterly" } ) %>
  <% available_months = BookingServiceLine.all.map { |x| [x.date_of_booking("%B"), x.date_of_booking("%B")] }.uniq { |x| x } %>
  <% available_years = BookingServiceLine.all.map { |x| [x.date_of_booking("%Y"), x.date_of_booking("%Y")] }.uniq { |x| x } %>
  
  <%= select_tag(:month_select, options_for_select(available_months), name: "month", class: "control hidden", data: { scope: "monthly" } ) %>
  <%= select_tag(:year_select, options_for_select(available_years), name: "year", class: "control hidden", data: { scope: "yearly monthly quarterly" } ) %>
    
  </div>
  <div class="grid-reports-chart">
    <%= column_chart reports_revenue_by_service_json_path%>
  </div>
</div>